# Generated by Django 3.2.4 on 2021-06-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20210623_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='test',
        ),
    ]
