# Generated by Django 3.2.4 on 2021-06-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_rename_comment_comment_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='test',
            new_name='comment',
        ),
    ]
